<?php

require_once dirname(__FILE__) . '/../../../Class/Registry.php';

/**
 * Test class for Registry.
 * Generated by PHPUnit on 2011-07-06 at 02:51:16.
 */
class RegistryTest extends PHPUnit_Framework_TestCase {
	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {

	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testDefined().
	 */
	public function testDefined() {
		Registry::set ('a', 5);
		
		$this->assertTrue (Registry::defined ('a'));
		
		$this->assertFalse (Registry::defined ('b'));
		
		Registry::set ('b', null);
		
		$this->assertFalse (Registry::defined ('b'));
		
		Registry::set ('a', 0);
		
		$this->assertTrue (Registry::defined ('a'));
	}

	/**
	 * @todo Implement testGet().
	 */
	public function testGet() { 
		
		Registry::set ('a', 5);
		Registry::set ('b', 0);
		
		$this->assertEquals (Registry::get ('a'), 5);
		$this->assertEquals (Registry::get ('b'), 0);
		
		Registry::set ('a', 0);
		Registry::set ('b', 5);
		
		$this->assertEquals (Registry::get ('a'), 0);
		$this->assertEquals (Registry::get ('b'), 5);
	}

	/**
	 * @todo Implement testSet().
	 */
	public function testSet() {
		Registry::set ('a', 5);
		Registry::set ('b', 0);
		
		$this->assertEquals (Registry::get ('a'), 5);
		$this->assertEquals (Registry::get ('b'), 0);
		
		Registry::set ('a', 0);
		Registry::set ('b', 5);
		
		$this->assertEquals (Registry::get ('a'), 0);
		$this->assertEquals (Registry::get ('b'), 5);
	}

	/**
	 * @todo Implement testSget().
	 */
	public function testSget() {
		Registry::set ('a', 5);
		
		$this->assertEquals (Registry::sget ('a'), 5);
		$this->assertNull (Registry::sget ('e'));
		$this->assertNull (Registry::sget ('d'));
		
		Registry::set ('d', 15);
		
		$this->assertNotNull (Registry::sget ('d'));
		
	}

	/**
	 * @todo Implement testRget().
	 */
	public function testRget() {
		$a = 5;
		
		Registry::rset ('a', $a); 
	
		$this->assertEquals (Registry::rget ('a'), 5);
		
		$a = 6;
		
		$this->assertEquals (Registry::rget ('a'), 6);
		
		$a = null;
		
		$this->assertNull (Registry::rget ('a'));
		
		$b = &Registry::rget ('a');
		
		$b = 7;
		
		$this->assertEquals (Registry::rget ('a'), 7);
	}

	/**
	 * @todo Implement testRset().
	 */
	public function testRset() {
		$a = 5;
		
		Registry::rset ('a', $a); 
	
		$this->assertEquals (Registry::rget ('a'), 5);
		
		$a = 6;
		
		$this->assertEquals (Registry::rget ('a'), 6);
		
		$a = null;
		
		$this->assertNull (Registry::rget ('a'));
		
		$b = &Registry::rget ('a');
		
		$b = 7;
		
		$this->assertEquals (Registry::rget ('a'), 7);
	}

}

?>
