<?php

require_once dirname(__FILE__) . '/../../../Class/Router.php';

/**
 * Test class for Router.
 * Generated by PHPUnit on 2011-07-08 at 07:10:43.
 */
class RouterTest extends PHPUnit_Framework_TestCase {

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$ds = Data_Source_Manager::get ('default');
		
		DDS::setDataSource ($ds);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testGetRoute().
	 */
	public function testGetRoute() {
		$_SERVER ['REQUEST_URI'] = '/r/xg12?sad=sd&sd=sd&sd';
		
		$route = Route::byUrl ('/r/sad');
		
		$router_route = Router::getRoute ();
		
		$this->assertEquals ($route, $router_route); 
		
		$_SERVER ['REQUEST_URI'] = null;
		
		$route = Route::byUrl ('aaar/sad');
		
		$router_route = Router::getRoute ();
		
		$this->assertNotEquals ($route, $router_route); 
		
	}

}

?>
