<?php

require_once dirname(__FILE__) . '/../../../Class/Tracer.php';

/**
 * Test class for Tracer.
 * Generated by PHPUnit on 2011-08-19 at 04:09:55.
 */
class TracerTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Tracer
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Tracer;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testLog().
	 */
	public function testLog() {
		Tracer::log ('base level');
		sleep (1);
		Tracer::log ('step into', 1);
		sleep (1);
		Tracer::log ('nothing');
		sleep (1);
		Tracer::log ('with type', 0, 'test');
		sleep (1);
		Tracer::log ('level back', -1);
		$this->assertTrue (count (Tracer::$logs) >= 5);
	}
	
	/**
	 * @todo Implement testFlushFile().
	 */
	public function testFlushFile() {
		$file = 'C:/temp/tracer.txt';
		Tracer::flushFile ($file);
		$this->assertFileExists ($file);
	}

	/**
	 * @todo Implement testMicrotime().
	 * @depends testLog
	 */
	public function testMicrotime() {
		$start = Tracer::microtime ();
		
		for ($i = 1; $i < 10; ++$i)
		{
			sleep (1);
			$delta = Tracer::microtime () - $start;
			
			$this->assertEquals ($i, $delta, 'lag', 0.1);
		}
	}

}

?>
