<?php

require_once '/var/www/vipgeo.local/IcEngine/Model/Component/Rating/Log.php';

/**
 * Test class for Component_Rating_Log.
 * Generated by PHPUnit on 2011-09-09 at 07:31:19.
 */
class Component_Rating_LogTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Component_Rating_Log
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Component_Rating_Log;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
?>
