<?php

require_once dirname(__FILE__) . '/../../../../Ice/Model/Captcha.php';

/**
 * Test class for Captcha.
 * Generated by PHPUnit on 2011-07-12 at 07:36:25.
 */
class CaptchaTest extends PHPUnit_Framework_TestCase {

 
	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		
		$ds = Data_Source_Manager::get ('default');
		
		DDS::setDataSource ($ds);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testAccept().
	 */
	public function testAccept() {
		
		$captcha = Captcha::accept ();
		
		$captcha->save ();
		
		$id = $captcha->key ();
		
		$captcha_2 = Model_Manager::byKey (
			'Captcha',
			$id
		);
		
		$this->assertEquals ($captcha, $captcha_2);
	}

	/**
	 * @todo Implement testCheck().
	 */
	public function testCheck() {
		$this->assertFalse (Captcha::check ());
		
		$_POST ['captcha_hash'] = 'fake';
		
		$this->assertFalse (Captcha::check ());
		
		$_SESSION ['captcha'] = 'fake';
		
		$this->assertTrue (Captcha::check ());
		
		$this->assertFalse (Captcha::check ('Fake'));
	}

}

?>
