<?php

namespace Ice;

require_once dirname (__FILE__) . '/../../../../../App/Class/Manager/Abstract.php';

/**
 * Test class for Manager_Abstract.
 * Generated by PHPUnit on 2012-02-02 at 06:25:00.
 */
class Manager_AbstractTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var Manager_Abstract
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp ()
	{

	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown ()
	{

	}

	/**
	 * @todo Implement testByName().
	 */
	public function testByName ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCompleteClassName().
	 */
	public function testCompleteClassName ()
	{
		$tests = array (
			array (
				'Smarty',
				'Ice\\View_Render',
				'Ice\\View_Render_Smarty'
			),
			array (
				'Gb\\Other',
				'Ice\\View_Render',
				'Gb\\View_Render_Other'
			),
			array (
				'Ice\\Smarty',
				'Ice\\View_Render',
				'Ice\\View_Render_Smarty'
			),
			array (
				'Smarty',
				'View_Render',
				'View_Render_Smarty'
			),
			array (
				'Gb\\Smarty',
				'View_Render',
				'Gb\\View_Render_Smarty'
			)
		);

		foreach ($tests as $i => $test)
		{
			$actual = Manager_Abstract::completeClassName (
				$test [0],
				$test [1]
			);

			$this->assertEquals ($test [2], $actual, 'Step: ' . $i);
		}
	}

	/**
	 * @todo Implement testConfig().
	 */
	public function testConfig ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetName().
	 */
	public function testGetName ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGet().
	 */
	public function testGet ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

}

?>
