<?php

require_once dirname (__FILE__) . '/../../../../../../Class/Data/Validator/Registration/Password.php';

/**
 * Test class for Data_Validator_Registration_Password.
 * Generated by PHPUnit on 2011-07-06 at 03:16:09.
 */
class Data_Validator_Registration_PasswordTest extends PHPUnit_Framework_TestCase
{

	/**
	 * @var Data_Validator_Registration_Password
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp ()
	{
		$this->object = new Data_Validator_Registration_Password;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown ()
	{
		
	}

	/**
	 * @todo Implement testValidate().
	 */
	public function testValidate ()
	{
		$tests = array (
			'1'										=> false,
			'fuck'									=> false,
			'password'								=> true,
			'gj9834uejt98w53i'						=> true,
			'12345678901234567890'					=> true,
			'CoolToHate.WelcomeToAmericana'			=> false,
			'!@#$%^&*()'							=> null
		);
		
		$results = array ();
		foreach ($tests as $test => $result)
		{
			$valid = $this->Data_Validator_Registration_Password->validate ($test);
			if (is_null ($result))
			{
				$results [$test] = $valid;
			}
			else
			{
				$this->assertEquals ($result, $valid);
			}
		}
		
		var_dump ($results);
	}

	/**
	 * @todo Implement testValidateEx().
	 */
	public function testValidateEx ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

}

?>
