<?php

require_once dirname (__FILE__) . '/../../../../Model/Tiny/Link.php';

/**
 * Test class for Tiny_Link.
 * Generated by PHPUnit on 2011-07-06 at 03:17:58.
 */
class Tiny_LinkTest extends PHPUnit_Framework_TestCase
{

	/**
	 * @var Tiny_Link
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp ()
	{
		$this->object = new Tiny_Link;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown ()
	{
		
	}

	/**
	 * @todo Implement testIntEncode().
	 */
	public function testIntEncode ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testIntDecode().
	 */
	public function testIntDecode ()
	{
		$max = 2000000000;
		$random_step = (int) ($max / 6);
		
		$i = 1;
		while ($i < $max)
		{
			$d = Tiny_Link::intDecode ($i);
			$this->assertEquals ($i, Tiny_Link::intEncode ($d));
			$i += rand(1, $random_step);
		}
	}

	/**
	 * @todo Implement testByLink().
	 */
	public function testByLink ()
	{
		$max = 2000000000;
		$random_step = (int) ($max / 6);
		
		$i = 1;
		while ($i < $max)
		{
			$d = Tiny_Link::intEncode ($i);
			$this->assertEquals ($i, Tiny_Link::intDecode ($d));
			$i += rand(1, $random_step);
		}
	}

	/**
	 * @todo Implement testByShort().
	 */
	public function testByShort ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testShortLink().
	 */
	public function testShortLink ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

}

?>
