<?php

require_once dirname(__FILE__) . '/../../../../Class/Helper/Header.php';

/**
 * Test class for Helper_Header.
 * Generated by PHPUnit on 2011-07-08 at 05:41:27.
 */
class Helper_HeaderTest extends PHPUnit_Framework_TestCase {


	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {

	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testSetStatus().
	 */
	public function testSetStatus() {
		$hh = Helper_Header::$statuses [Helper_Header::E403];
		
		@Helper_Header::setStatus (Helper_Header::E403, true);
		
		$headers = Helper_Header::$statuses;
		
		$exists = false;
		
		foreach ($headers as $h)
		{
			if ($h [0] == $hh [0])
			{
				$exists = true;
			}
		}
		
		$this->assertTrue ($exists);
		
		$hh = Helper_Header::$statuses [Helper_Header::E404];
		
		@Helper_Header::setStatus (Helper_Header::E404, false);
		
		$headers = Helper_Header::$statuses;
		
		$exists = false;
		
		foreach ($headers as $h)
		{
			if ($h [0] == $hh [0])
			{
				$exists = true;
			}
		}
		
		$this->assertTrue ($exists);
	}

	/**
	 * @todo Implement testRedirect().
	 */
	public function testRedirect() {
		flush ();
		
		Helper_Header::redirect ('fake');
		
		Helper_Header::redirect ('fake', 404);
	}

	/**
	 * @todo Implement testJsRedirect().
	 */
	public function testJsRedirect() {
		Helper_Header::jsRedirect ('fake');
	}

}

?>
