<?php

require_once dirname (__FILE__) . '/../../../../Class/Helper/String.php';

/**
 * Test class for Helper_String.
 * Generated by PHPUnit on 2011-07-06 at 03:37:45.
 */
class Helper_StringTest extends PHPUnit_Framework_TestCase
{

	/**
	 * @var Helper_String
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp ()
	{
		$this->object = new Helper_String;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown ()
	{
		
	}

	/**
	 * @todo Implement testAfter().
	 */
	public function testAfter ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testAutoIconv().
	 */
	public function testAutoIconv ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testBefore().
	 */
	public function testBefore ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testBegin().
	 */
	public function testBegin ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testBetween().
	 */
	public function testBetween ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCharset_x_utf8().
	 */
	public function testCharset_x_utf8 ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCharset_x_windows1251().
	 */
	public function testCharset_x_windows1251 ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testEnd().
	 */
	public function testEnd ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testExtractNums().
	 */
	public function testExtractNums ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testIdsExtract().
	 */
	public function testIdsExtract ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testPrefixedInts().
	 */
	public function testPrefixedInts ()
	{
		$tests = array (
			'a1bb22c333', '444a4b4c4d4', '1234', 'abcd', '1a1', 
			'y2010m12d2', 'sgn+2ch'
		);
		echo "\r\n";
		foreach ($tests as $test)
		{
			echo $test . ' => ';
			$result = Helper_String::prefixedInts ($test);
			print_r ($result);
			echo "\r\n\r\n";
		}
	}

	/**
	 * @todo Implement testSmartPreview().
	 */
	public function testSmartPreview ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testStr2int().
	 */
	public function testStr2int ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testTruncateUtf8().
	 */
	public function testTruncateUtf8 ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSecure().
	 */
	public function testSecure ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testUtf8_win1251().
	 */
	public function testUtf8_win1251 ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testWin1251_utf8().
	 */
	public function testWin1251_utf8 ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

}

?>
