<?php

require_once dirname (__FILE__) . '/../../../../Class/Helper/Color.php';

/**
 * Test class for Helper_Color.
 * Generated by PHPUnit on 2011-07-06 at 03:28:19.
 */
class Helper_ColorTest extends PHPUnit_Framework_TestCase
{

	/**
	 * @var Helper_Color
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp ()
	{
//		$this->object = new Helper_Color;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown ()
	{
		
	}

	/**
	 * @todo Implement testCssToRgb().
	 */
	public function testCssToRgb ()
	{
		for ($i = 1; $i < 999999; $i += rand (100, 999))
		{
			$rgb = Helper_Color::cssToRgb ($i);
			$this->assertEquals (count ($rgb), 3);
		}
	}

}

?>
