<?php

require_once dirname(__FILE__) . '/../../../../Class/Helper/YMaps.php';

/**
 * Test class for Helper_YMaps.
 * Generated by PHPUnit on 2011-07-19 at 17:51:13.
 */
class Helper_YMapsTest extends PHPUnit_Framework_TestCase
{

	/**
	 * @var Helper_YMaps
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp ()
	{
		$this->object = new Helper_YMaps;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown ()
	{
		
	}

	/**
	 * @todo Implement testGeocodePoint().
	 */
	public function testGeocodePoint ()
	{
		$key = 'AKLl3E0BAAAAgKZeVwIA6Q_--pjvX1BrB499AUHOvigaDe4AAAAAAAAAAACv6MQyaLTZHlEKMC8f-Mj5ADcrdA==';
		$inputs = array (
			array ('12312fafa', 'Россия, Москва'),
			array ($key, 'Россия, Москва'),
			array ($key, 'Россия, Новокузнецк')
		);
		
		$outputs = array (
			null,
			array (37.609218, 55.753559),	// Москва
			array (87.113487, 53.740749)	// Новокузнецк
		);
		// Remove the following lines when you implement this test.
		foreach ($inputs as $i => $input)
		{
			$r = Helper_YMaps::geocodePoint ($input [0], $input [1]);
			
			if ($r)
			{
				$r = (string) $r->GeoObject->Point->pos;
				$r = explode (' ', $r);
			}
			
			$this->assertEquals ($outputs [$i], $r);
		}
	}
	
	/**
	 * 
	 */
	public function testDistance ()
	{
		$inputs = array (
			array (
				array (0, 0),
				array (1, 1)
			),
			array (
				array (37.609218, 55.753559),	// Москва
				array (87.113487, 53.740749)	// Новокузнецк
			)
		);
		
		$outputs = array (
			157425.49671073369,
			3113479.120662418
		);
		
		foreach ($inputs as $i => $input)
		{
			$r = Helper_YMaps::distance ($input [0], $input [1]);
			var_dump ($r);
			$this->assertEquals ($outputs [$i], $r);
		}
	}
	
	public function testDistanceAlt ()
	{
		$inputs = array (
			array (
				array (0, 0),
				array (1, 1)
			),
			array (
				array (37.609218, 55.753559),	// Москва
				array (87.113487, 53.740749)	// Новокузнецк
			)
		);
		
		$outputs = array (
			157425.49671073369,
			3113479.120662418
		);
		
		foreach ($inputs as $i => $input)
		{
			$r = Helper_YMaps::distanceAlt (
				$input [0][0], $input [0][1],
				$input [1][0], $input [1][1]
			);
			$this->assertEquals (
				(float) $outputs [$i],
				(float) $r,
				'More than epsilon',
				$outputs [$i] * 0.01
			);
		}

	}
	
	public function testParseYandexRasp ()
	{
		$html = file_get_contents ('/var/test.txt');
		
		var_dump (Helper_YMaps::parseYandexRasp ($html));
	}
	
	public function testTimeInWay ()
	{
		$times = Helper_YMaps::timeInWay (
			'Новокузнецк',
			'Москва',
			array ('type' => 'plane')
		);
		
		var_dump ($times);
	}

}

