<?php

require_once dirname (__FILE__) . '/../../../../Class/Helper/Date.php';

/**
 * Test class for Helper_Date.
 * Generated by PHPUnit on 2011-07-06 at 03:10:30.
 */
class Helper_DateTest extends PHPUnit_Framework_TestCase
{

	/**
	 * @var Helper_Date
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp ()
	{
		$this->object = new Helper_Date;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown ()
	{
		
	}

	/**
	 * @todo Implement testCmpUnix().
	 */
	public function testCmpUnix ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testDateByWeek().
	 */
	public function testDateByWeek ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testDaysInMonth().
	 */
	public function testDaysInMonth ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testEraDayNum().
	 */
	public function testEraDayNum ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testEraWeekNum().
	 */
	public function testEraWeekNum ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetmicrotime().
	 */
	public function testGetmicrotime ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testMonthEqual().
	 */
	public function testMonthEqual ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testMonthName().
	 */
	public function testMonthName ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testNextTime().
	 */
	public function testNextTime ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testParseDateTime().
	 */
	public function testParseDateTime ()
	{
		$this->assertEquals (date ('Y-m-d H:i:s'), Helper_Date::toUnix ());
		$test_time = time () + 10050;
		$this->assertEquals (
			date ('Y-m-d H:i:s', $test_time),
			Helper_Date::toUnix ($test_time)
		);
	}

	/**
	 * @todo Implement testSecondsBetween().
	 */
	public function testSecondsBetween ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testStrToTimestamp().
	 */
	public function testStrToTimestamp ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testStrToTimeDef().
	 */
	public function testStrToTimeDef ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testToCasualDate().
	 */
	public function testToCasualDate ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testToDateTime().
	 */
	public function testToDateTime ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testToUnix().
	 */
	public function testToUnix ()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
				'This test has not been implemented yet.'
		);
	}

}

?>
