<?php

require_once dirname(__FILE__) . '/../../../../../vipgeo.ru/IcEngine/Class/Config/Array.php';

/**
 * Test class for Config_Array.
 * Generated by PHPUnit on 2011-07-13 at 05:40:26.
 * @author Markov
 */
class Config_ArrayTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Config_Array
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {

	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testMerge().
	 */
	public function testMerge() {
		
		$config_array = new Config_Array (array ('b' => 2));
		$this->assertEquals ($config_array->b, 2);
		
		$config_array->merge (array ('a' => 1));
		$this->assertEquals ($config_array->a, 1);
		
		$config_array->merge (array ('a' => 5));
		$this->assertNotEquals ($config_array->a, 5);
		$this->assertEquals ($config_array->a, 1);
	}

}

?>
