<?php

require_once dirname(__FILE__) . '/../../../../Model/Crypt/Xxtea.php';

/**
 * Test class for Crypt_Xxtea.
 * Generated by PHPUnit on 2011-07-06 at 03:01:17.
 */
class Crypt_XxteaTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Crypt_Xxtea
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Crypt_Xxtea;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testDecode().
	 */
	public function testDecode()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testEncode().
	 */
	public function testEncode()
	{
		$tests = array (
			'asdjfkljdslfijasdlifjalsij liasdfa',
			'0',
			'',
			'JFiljasjdf 9jaljljdfjal4jofjlajaflds',
			'дваод фышоДОВОА ОЫВао офдшоа фывоаш фыво афод',
			'1234567890-!@#$%^&*()_'
		);
		
		$keys = array (
			'',
			'123456789',
			'0',
			'jldjf asd fj8jJF sdfsdjfв фыва фыва фывадфышдшодшодОДОДШО'
		);
		
		foreach ($tests as $test)
		{
			foreach ($keys as $key)
			{
				$crypted = $this->Crypt_Xxtea->encode ($test, $key);
				$uncrypted = $this->Crypt_Xxtea->decode ($crypted, $key);
				$this->assertEquals ($test, $uncrypted);
			}
		}
	}

}


