<?php

require_once dirname(__FILE__) . '/../../../Model/Month.php';

/**
 * Test class for Month.
 * Generated by PHPUnit on 2011-07-05 at 14:06:01.
 */
class MonthTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Month
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Month;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

}

?>
